- name: install maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: include app pre setup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-pre-setup

- name: install maven dependencies
  ansible.built.shell: mvn clean package && mv target/{{component}}-1.0.jar {{component}}.jar
  args:
      chdir: /home/roboshop/{{component}}
  become_user: roboshop

- name: include systemd
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd