- name: Clean labauto
  shell: sudo labauto clean

- name: Setup Hostname
  ansible.builtin.shell: set-hostname {{component}}

- name: Install Prometheus Node Exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: client